import pytest

from openprogram.security.safe_http import (
    CONSUMER_REGISTRY,
    OutboundSecurityConfig,
    safe_client,
)


COMPATIBILITY_FIXTURES = {
    "tool.web_fetch": (
        "untrusted_public",
        "GET",
        "https://cdn.example.test",
        443,
        ("http", "https"),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        5_242_881,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "tool.web_search.fixed_api": (
        "fixed_public_service",
        "POST",
        "https://api.exa.ai",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        None,
    ),
    "tool.web_search.configured_api": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
    "tool.image_api.fixed": (
        "fixed_public_service",
        "POST",
        "https://api.openai.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        None,
    ),
    "tool.image_api.configured": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
    "tool.image_result.download": (
        "untrusted_public",
        "GET",
        "https://cdn.example.test",
        443,
        ("http", "https"),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("image/", "application/octet-stream"),
        "none",
        False,
        None,
    ),
    "channel.attachment.download": (
        "untrusted_public",
        "GET",
        "https://cdn.example.test",
        443,
        ("http", "https"),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        20_971_520,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "channel.telegram.api": (
        "fixed_public_service",
        "POST",
        "https://api.telegram.org",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "exact_origin",
    ),
    "channel.discord.api": (
        "fixed_public_service",
        "PATCH",
        "https://discord.com",
        443,
        ("https",),
        ("GET", "HEAD", "PATCH", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "exact_origin",
    ),
    "channel.discord.gateway_sdk": (
        "fixed_public_service",
        "POST",
        "https://discord.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "disabled",
    ),
    "channel.slack.api": (
        "fixed_public_service",
        "POST",
        "https://slack.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "exact_origin",
    ),
    "channel.slack.gateway_sdk": (
        "fixed_public_service",
        "POST",
        "https://slack.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "disabled",
    ),
    "channel.slack.attachment": (
        "fixed_public_service",
        "GET",
        "https://files.slack.com",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "same_origin",
        5,
        20_971_520,
        ("application/", "audio/", "image/", "text/", "video/"),
        "same_origin",
        False,
        None,
    ),
    "channel.slack.generated_asset.upload": (
        "fixed_public_service",
        "POST",
        "https://files.slack.com",
        443,
        ("https",),
        ("POST",),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "none",
        False,
        None,
    ),
    "channel.telegram.attachment": (
        "fixed_public_service",
        "GET",
        "https://api.telegram.org",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "same_origin",
        5,
        20_971_520,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "channel.wechat.api": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "exact_origin",
    ),
    "channel.feishu.api": (
        "fixed_public_service",
        "POST",
        "https://open.feishu.cn",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        "exact_origin",
    ),
    "channel.matrix.configured": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "exact_origin",
    ),
    "channel.generated_asset.download": (
        "untrusted_public",
        "GET",
        "https://cdn.example.test",
        443,
        ("http", "https"),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "skills.github.catalog": (
        "fixed_public_service",
        "GET",
        "https://github.com",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "skills.configured.catalog": (
        "configured_service",
        "GET",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD"),
        None,
        "same_origin",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "same_origin",
        True,
        None,
    ),
    "plugins.marketplace": (
        "configured_service",
        "GET",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD"),
        None,
        "same_origin",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "same_origin",
        True,
        None,
    ),
    "plugins.autoupdate": (
        "fixed_public_service",
        "GET",
        "https://pypi.org",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "updater.github": (
        "fixed_public_service",
        "GET",
        "https://api.github.com",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "updater.pip": (
        "fixed_public_service",
        "GET",
        "https://pypi.org",
        443,
        ("https",),
        ("GET", "HEAD"),
        (80, 443),
        "public",
        5,
        33_554_432,
        ("application/", "audio/", "image/", "text/", "video/"),
        "none",
        False,
        None,
    ),
    "provider.fixed_api": (
        "fixed_public_service",
        "POST",
        "https://api.openai.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        None,
    ),
    "provider.configured_api": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
    "provider.oauth.fixed": (
        "fixed_public_service",
        "POST",
        "https://accounts.google.com",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        None,
    ),
    "provider.google.sdk": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "injected_transport",
    ),
    "provider.openai.sdk": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "injected_transport",
    ),
    "provider.anthropic.sdk": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "injected_transport",
    ),
    "mcp.configured.http": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "injected_transport",
    ),
    "mcp.configured.sse": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "injected_transport",
    ),
    "mcp.loopback.callback": (
        "loopback_callback",
        "GET",
        "http://127.0.0.1:17654",
        17654,
        ("http",),
        ("GET", "HEAD"),
        None,
        "deny",
        1,
        1_048_576,
        ("application/", "text/"),
        "none",
        False,
        None,
    ),
    "tts.fixed_api": (
        "fixed_public_service",
        "POST",
        "https://api.elevenlabs.io",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("audio/", "application/octet-stream"),
        "same_origin",
        False,
        "exact_origin",
    ),
    "tts.configured_api": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("audio/", "application/octet-stream"),
        "same_origin",
        True,
        "exact_origin",
    ),
    "tts.edge_sdk": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        "disabled",
    ),
    "webui.mcp.catalog": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
    "webui.model_listing.fixed": (
        "fixed_public_service",
        "POST",
        "https://models.dev",
        443,
        ("https",),
        ("GET", "HEAD", "POST"),
        (80, 443),
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        False,
        None,
    ),
    "webui.model_listing.configured": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
    "runtime.local_probe": (
        "configured_service",
        "POST",
        "http://configured.example.test:17654",
        17654,
        ("http", "https"),
        ("GET", "HEAD", "POST"),
        None,
        "same_origin",
        5,
        16_777_216,
        ("application/", "text/"),
        "same_origin",
        True,
        None,
    ),
}


def test_every_registry_consumer_has_a_literal_compatibility_fixture() -> None:
    assert set(COMPATIBILITY_FIXTURES) == set(CONSUMER_REGISTRY)


@pytest.mark.parametrize("consumer, expected", COMPATIBILITY_FIXTURES.items())
def test_literal_fixture_matches_the_real_policy_boundary(consumer, expected) -> None:
    (
        trust_class,
        method,
        origin,
        port,
        schemes,
        methods,
        ports,
        redirect_policy,
        redirects,
        body_cap,
        mime_prefixes,
        credential_policy,
        owner_exceptions,
        sdk_disposition,
    ) = expected
    spec = CONSUMER_REGISTRY[consumer]

    assert spec.trust_class.value == trust_class
    assert spec.allowed_schemes == frozenset(schemes)
    assert spec.allowed_methods == frozenset(methods)
    assert spec.allowed_ports == (None if ports is None else frozenset(ports))
    assert spec.redirect_policy == redirect_policy
    assert spec.max_redirects == redirects
    assert spec.max_decoded_body_bytes == body_cap
    assert spec.accepted_mime_prefixes == mime_prefixes
    assert spec.credential_origin_policy == credential_policy
    assert spec.allow_owner_exceptions is owner_exceptions
    assert (
        None if spec.sdk_disposition is None else spec.sdk_disposition.value
    ) == sdk_disposition

    kwargs = {}
    if trust_class == "configured_service":
        kwargs["configured_origin"] = origin
    if trust_class == "loopback_callback":
        kwargs["callback_origin"] = origin
    resolver = lambda _host, _port: (
        ("127.0.0.1",) if trust_class == "loopback_callback" else ("93.184.216.34",)
    )
    with safe_client(
        consumer, security=OutboundSecurityConfig(resolver=resolver), **kwargs
    ) as client:
        decision = client._transport._evaluate(method, origin + "/compatibility")

    assert decision.origin == origin
    assert decision.port == port
