"""Prompt text for the task tool (description shown to the LLM)."""
from __future__ import annotations

DESCRIPTION = (
    "Spawn another agent in the same session and run one turn against "
    "it. Returns the spawned agent's final reply (wait=True, default) "
    "or a task_id to await later (wait=False).\n"
    "\n"
    "Context modes, chosen per call:\n"
    "  clean (DEFAULT): the agent starts at a new root seeing ONLY the "
    "prompt — no history, no prior tool results. Use it whenever you "
    "can write a self-contained instruction; pack everything it needs "
    "into the prompt. Cheaper and more focused.\n"
    "  inherit: the agent forks off this turn and sees the whole "
    "conversation chain. Use it only when the sub-task genuinely "
    "depends on the running dialogue. Costs more tokens and carries "
    "noise from prior tool calls.\n"
    "\n"
    "If YOU are a spawned agent this tool is unavailable — do the work "
    "with your own tools. Re-delegation is refused (depth cap 1).\n"
    "\n"
    "The reply lands as a branch in the session DAG; merge it back "
    "with merge_branches.\n"
    "\n"
    "Args:\n"
    "  prompt: full instruction. In 'clean' mode this is ALL it sees.\n"
    "  description: short label (1-3 words), used as the branch name.\n"
    "  agent_id: agent profile to run as. Defaults to this session's.\n"
    "  context: 'clean' (default) or 'inherit'.\n"
    "  wait: True (default) blocks and returns the final text. False "
    "returns a task_id immediately — use it to run agents in parallel, "
    "then call await_task(task_id)."
)
