"""Prompt text for the agent tool (description shown to the LLM)."""
from __future__ import annotations

DESCRIPTION = (
    "Spawn another agent in the same session and run one turn against "
    "it. Returns the spawned agent's final reply "
    "(run_in_background=false, default) or a task_id to await later "
    "(run_in_background=true). This is the ONE tool "
    "that creates new agents; to talk to an agent that already exists, "
    "use send_message instead.\n"
    "\n"
    "Context modes, chosen per call:\n"
    "  clean (DEFAULT): the agent starts at a new root seeing ONLY the "
    "prompt — no history, no prior tool results. Use it whenever you "
    "can write a self-contained instruction; pack everything it needs "
    "into the prompt. Cheaper and more focused.\n"
    "  inherit: the agent forks off this turn and sees the whole "
    "conversation chain. Use it only when the sub-task genuinely "
    "depends on the running dialogue. Costs more tokens and carries "
    "noise from prior tool calls.\n"
    "  'SID:MSG_ID': the agent forks off that exact node (any "
    "session), inheriting the chain up to it. Use it to branch a new "
    "line of work from a specific point in the DAG (node addresses "
    "come from list_agents / the chat history).\n"
    "\n"
    "If YOU are a spawned agent this tool is unavailable — do the work "
    "with your own tools. Re-delegation is refused (depth cap 1).\n"
    "\n"
    "The reply lands as a branch in the session DAG; merge it back "
    "with merge_branches.\n"
    "\n"
    "Args:\n"
    "  prompt: full instruction. In 'clean' mode this is ALL it sees.\n"
    "  description: short label (1-3 words), used as the branch name.\n"
    "  agent_id: agent profile to run as. Defaults to this session's.\n"
    "  context: 'clean' (default), 'inherit', or 'SID:MSG_ID'.\n"
    "  run_in_background: Set to true to run this agent in the "
    "background. You will be notified when it completes. Retrieve the "
    "result with task_output(task_id), or stop the agent early with "
    "task_stop(task_id)."
)
