#!/usr/bin/env python3
"""A CLI tool that takes a topic and generates a mini-lesson: first identify 3 key concepts, then explain each one, then synthesize a takeaway. Generated by agentic create-app."""

import argparse
from agentic import agentic_function, create_runtime

runtime = create_runtime()

@agentic_function
def identify_key_concepts(topic: str) -> str:
    """Identify 3 key concepts related to the topic."""
    return runtime.exec(content=[
        {"type": "text", "text": f"Identify 3 key concepts about {topic}."},
    ])

@agentic_function
def explain_concepts(concepts: str) -> str:
    """Explain each of the identified key concepts."""
    return runtime.exec(content=[
        {"type": "text", "text": f"Explain these concepts: {concepts}."},
    ])

@agentic_function
def synthesize_takeaway(explanation: str) -> str:
    """Synthesize a takeaway from the explanations."""
    return runtime.exec(content=[
        {"type": "text", "text": f"Synthesize a takeaway from these explanations: {explanation}."},
    ])

def main():
    parser = argparse.ArgumentParser(description="Generate a mini-lesson from a given topic.")
    parser.add_argument("topic", help="The topic for the mini-lesson")
    parser.add_argument("--provider", default=None, help="LLM provider override")
    parser.add_argument("--model", default=None, help="Model override")
    args = parser.parse_args()

    global runtime
    runtime = create_runtime(provider=args.provider, model=args.model)

    concepts = identify_key_concepts(topic=args.topic)
    explanation = explain_concepts(concepts=concepts)
    takeaway = synthesize_takeaway(explanation=explanation)

    print(takeaway)

if __name__ == "__main__":
    main()
