"""Persistent, machine-wide memory for OpenProgram agents.

Three layers:

1. **Short-term** (``short-term/YYYY-MM-DD.md``)
       Raw, append-only daily notes — agent observations, end-of-session
       summaries, candidate facts. Never edited. Source of truth for
       what was actually said / observed in conversations.

2. **Wiki** (``wiki/<type>/<page>.md``)
       Curated, structured knowledge with frontmatter (claims, evidence,
       confidence, sources). Maintained by the sleep process; the agent
       reads but does not directly edit. Karpathy's LLM Wiki pattern.

3. **Core** (``core.md``)
       <2KB always-on snapshot injected into every session's system
       prompt. Regenerated by the sleep process from the highest-signal
       wiki entries. Hermes-style frozen system-prompt block.

Sleep (background consolidation) runs nightly via the worker cron and
promotes short-term → wiki, regenerates core, surfaces reflections.

The agent interacts via lifecycle hooks (``MemoryProvider``) and four
tools: ``memory_note``, ``memory_recall``, ``memory_reflect``, ``memory_get``.

Storage location: ``<state>/memory/`` (profile-global by default —
shared across every agent and conversation on the machine).
"""
from . import store

__all__ = ["store"]
