"""``core.md`` — the always-on memory snapshot.

Tiny (<2 KB) document regenerated by the sleep process, injected into
every agent's system prompt at session start. Frozen during a session
so the LLM's prefix cache survives.

Format mirrors Hermes' MEMORY.md / USER.md banner so users coming from
that ecosystem feel at home.
"""
from __future__ import annotations

from pathlib import Path

from . import store
from .schema import WikiPage, today_iso

CORE_BUDGET_CHARS = 2048
CORE_HEADER = "OpenProgram memory (machine-wide)"


def render(entries: list[str], *, last_consolidated: str = "") -> str:
    """Render core.md from a list of pre-formatted entry strings.

    Caller is responsible for picking the highest-signal entries and
    keeping each one short. We just lay them out.
    """
    rule = "═" * 60
    when = last_consolidated or today_iso()
    used = sum(len(e) for e in entries)
    pct = int(round(used / CORE_BUDGET_CHARS * 100))
    head = (
        f"{rule}\n"
        f"{CORE_HEADER} — {pct}% ({used}/{CORE_BUDGET_CHARS} chars), "
        f"last consolidated {when}\n"
        f"{rule}\n"
    )
    body = "\n§\n".join(entries)
    foot = "\n\n[for full context use memory_recall <query>]\n"
    return head + body + foot


def write(entries: list[str], *, last_consolidated: str = "") -> Path:
    """Replace ``core.md`` with fresh content."""
    text = render(entries, last_consolidated=last_consolidated)
    path = store.core()
    path.write_text(text, encoding="utf-8")
    return path


def read() -> str:
    """Read raw ``core.md`` text. Empty string if it doesn't exist yet."""
    path = store.core()
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def system_prompt_block() -> str:
    """Return the block to inject into a system prompt.

    Returns an empty string when memory hasn't been set up yet, so callers
    can unconditionally append it.
    """
    raw = read()
    if not raw.strip():
        return ""
    return raw


def select_entries(pages: list[WikiPage], *, budget: int = CORE_BUDGET_CHARS) -> list[str]:
    """Pick the highest-confidence claims that fit the budget.

    Default scoring: confidence × log(1 + n_sources). Caller can pass
    a pre-ranked list; this is a sensible default for the sleep deep
    phase to use.
    """
    import math
    scored: list[tuple[float, str]] = []
    for p in pages:
        for c in p.claims:
            if c.status == "superseded":
                continue
            score = c.confidence * (1.0 + math.log1p(len(c.sources)))
            scored.append((score, _format_claim(p, c)))

    scored.sort(reverse=True)
    out: list[str] = []
    used = 0
    for _, line in scored:
        if used + len(line) + 4 > budget:
            continue
        out.append(line)
        used += len(line) + 4
    return out


def _format_claim(page: WikiPage, claim) -> str:
    label = {
        "user": "USER",
        "entities": "ENTITY",
        "concepts": "CONCEPT",
        "procedures": "HOW-TO",
    }.get(page.type, page.type.upper())
    return f"{label}: {claim.text}"
