"""``core.md`` — the always-on memory snapshot.

Tiny (<2 KB) document regenerated by the sleep process, injected into
every agent's system prompt at session start. Frozen during a session
so the LLM's prefix cache survives.

Format mirrors Hermes' MEMORY.md / USER.md banner so users coming from
that ecosystem feel at home.
"""
from __future__ import annotations

from pathlib import Path

from . import store
from .schema import WikiPage, today_iso

CORE_BUDGET_CHARS = 2048
CORE_HEADER = "OpenProgram memory (machine-wide)"


def render(entries: list[str], *, last_consolidated: str = "") -> str:
    """Render core.md from a list of pre-formatted entry strings.

    Caller is responsible for picking the highest-signal entries and
    keeping each one short. We just lay them out.
    """
    rule = "═" * 60
    when = last_consolidated or today_iso()
    used = sum(len(e) for e in entries)
    pct = int(round(used / CORE_BUDGET_CHARS * 100))
    head = (
        f"{rule}\n"
        f"{CORE_HEADER} — {pct}% ({used}/{CORE_BUDGET_CHARS} chars), "
        f"last consolidated {when}\n"
        f"{rule}\n"
    )
    body = "\n§\n".join(entries)
    foot = "\n\n[for full context start with `memory_browse`]\n"
    return head + body + foot


def write(entries: list[str], *, last_consolidated: str = "") -> Path:
    """Replace ``core.md`` with fresh content."""
    text = render(entries, last_consolidated=last_consolidated)
    path = store.core()
    path.write_text(text, encoding="utf-8")
    return path


def read() -> str:
    """Read raw ``core.md`` text. Empty string if it doesn't exist yet."""
    path = store.core()
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


def system_prompt_block() -> str:
    """Return the block to inject into the system prompt.

    Three layers in one block:
      1. The compiled core.md (stable user prefs + active project facts,
         regenerated from the wiki by sleep deep)
      2. A one-line tool-surface pointer so the LLM knows how to dig
         deeper without us auto-injecting recall snippets
      3. Nothing else — keep this under ~2KB

    Returns "" when neither core nor wiki has any content yet so the
    block adds no system-prompt noise on a fresh install.
    """
    raw = read().strip()
    # Decide whether memory exists at all
    from . import store
    has_wiki = (store.wiki_dir() / "index.md").exists()
    if not raw and not has_wiki:
        return ""

    pointer = (
        "Memory tools available: `memory_browse` (catalog: wiki topics + "
        "recent days), `memory_get(target)` (read a wiki page or "
        "YYYY-MM-DD short-term file), `memory_recall(query)` (FTS "
        "fallback), `memory_reflect(query)` (multi-page synthesis), "
        "`memory_note(...)` (record an observation), `memory_ingest`/"
        "`memory_lint` (admin). Browse before recalling."
    )
    if raw:
        return raw.rstrip() + "\n\n" + pointer
    return pointer


def select_entries(pages: list[WikiPage], *, budget: int = CORE_BUDGET_CHARS) -> list[str]:
    """Pick the highest-confidence claims that fit the budget.

    Default scoring: confidence × log(1 + n_sources). Caller can pass
    a pre-ranked list; this is a sensible default for the sleep deep
    phase to use.
    """
    import math
    scored: list[tuple[float, str]] = []
    for p in pages:
        for c in p.claims:
            if c.status == "superseded":
                continue
            score = c.confidence * (1.0 + math.log1p(len(c.sources)))
            scored.append((score, _format_claim(p, c)))

    scored.sort(reverse=True)
    out: list[str] = []
    used = 0
    for _, line in scored:
        if used + len(line) + 4 > budget:
            continue
        out.append(line)
        used += len(line) + 4
    return out


def _format_claim(page: WikiPage, claim) -> str:
    label = {
        "user": "USER",
        "entities": "ENTITY",
        "concepts": "CONCEPT",
        "procedures": "HOW-TO",
    }.get(page.type, page.type.upper())
    return f"{label}: {claim.text}"
