"""Frontmatter / claims schema and YAML helpers.

A wiki page is a markdown file with a YAML frontmatter block at the top::

    ---
    type: entity                 # one of: entity | concept | procedure | user
    id: openprogram              # filename slug
    aliases: [op, openprogram]
    confidence: 0.9
    last_updated: 2026-05-09T12:34:00Z
    sources:
      - short-term/2026-05-08.md#L23
      - short-term/2026-05-09.md#L11
    claims:
      - text: "Backend daemon called 'worker', not 'daemon'"
        confidence: 1.0
        status: confirmed
      - text: "Uses Ink for TUI"
        confidence: 0.5
        status: disputed
    ---

    # Title

    Body prose, regenerated by sleep from the structured claims.

A short-term entry is a single markdown block::

    ## 14:32 — type: entity, tags: [user, env]
    User runs macOS arm64, zsh, ~/.agentic state dir.
    <!-- session: 0xabc, confidence: 0.8 -->

The schema is defined as plain dataclasses + minimal YAML I/O so we
don't pull in a heavyweight YAML library. PyYAML is available
(transitive dep of openai), but we keep our own loader/dumper to avoid
surprises with tag handling and to keep the format strictly versioned.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Any

# ── Types ────────────────────────────────────────────────────────────────────


@dataclass
class Claim:
    text: str
    confidence: float = 0.5
    status: str = "candidate"     # candidate | confirmed | disputed | superseded
    sources: list[str] = field(default_factory=list)


@dataclass
class WikiPage:
    type: str                        # entity | concept | procedure | user
    id: str                          # slug (filename without .md)
    title: str
    body: str = ""
    aliases: list[str] = field(default_factory=list)
    confidence: float = 0.5
    last_updated: str = ""           # ISO 8601 UTC
    sources: list[str] = field(default_factory=list)
    claims: list[Claim] = field(default_factory=list)
    extra: dict[str, Any] = field(default_factory=dict)  # forward-compat


@dataclass
class ShortTermEntry:
    timestamp: str                   # ISO 8601
    text: str
    type: str = "observation"        # observation | user-pref | env | project | etc.
    tags: list[str] = field(default_factory=list)
    session_id: str = ""
    confidence: float = 0.5


# ── YAML helpers (minimal) ───────────────────────────────────────────────────

_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)$", re.DOTALL)


def now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def today_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _yaml_dump(data: Any, indent: int = 0) -> str:
    """Tiny YAML serializer for our restricted schema.

    Supports str, int, float, bool, None, list, dict only. Strings with
    special chars get double-quoted with backslash escaping.
    """
    pad = "  " * indent
    if data is None:
        return "null"
    if isinstance(data, bool):
        return "true" if data else "false"
    if isinstance(data, (int, float)):
        return str(data)
    if isinstance(data, str):
        if data == "" or _needs_quoting(data):
            escaped = data.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            return f'"{escaped}"'
        return data
    if isinstance(data, list):
        if not data:
            return "[]"
        if all(isinstance(x, (str, int, float, bool)) and not _needs_quoting(str(x)) for x in data):
            return "[" + ", ".join(_yaml_dump(x) for x in data) + "]"
        lines = []
        for item in data:
            if isinstance(item, dict):
                first = True
                for k, v in item.items():
                    prefix = "- " if first else "  "
                    lines.append(f"{pad}{prefix}{k}: {_yaml_dump(v, indent + 1)}")
                    first = False
            else:
                lines.append(f"{pad}- {_yaml_dump(item, indent + 1)}")
        return "\n" + "\n".join(lines)
    if isinstance(data, dict):
        if not data:
            return "{}"
        lines = []
        for k, v in data.items():
            rendered = _yaml_dump(v, indent + 1)
            if rendered.startswith("\n"):
                lines.append(f"{pad}{k}:{rendered}")
            else:
                lines.append(f"{pad}{k}: {rendered}")
        return "\n" + "\n".join(lines) if indent > 0 else "\n".join(lines)
    raise TypeError(f"unsupported YAML value type: {type(data).__name__}")


def _needs_quoting(s: str) -> bool:
    if not s:
        return True
    if s[0] in "!&*-?{[]}|>%@`#":
        return True
    if s in ("null", "true", "false", "yes", "no", "on", "off"):
        return True
    if any(c in s for c in ":#\n\r\t\"'"):
        return True
    return False


def _yaml_load(text: str) -> dict[str, Any]:
    """Tiny YAML loader matching what we dump.

    We don't try to be a full YAML parser — only the subset we use.
    Falls back to PyYAML if available for anything tricky.
    """
    try:
        import yaml  # type: ignore[import-untyped]
        return yaml.safe_load(text) or {}
    except ImportError:
        return _yaml_load_native(text)


def _yaml_load_native(text: str) -> dict[str, Any]:
    """Native fallback parser for our restricted YAML."""
    result: dict[str, Any] = {}
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        raw = lines[i]
        line = raw.rstrip()
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if ":" not in line:
            i += 1
            continue
        key, _, val = line.partition(":")
        key = key.strip()
        val = val.strip()
        if not val:
            # Block — collect indented children. Could be list of dicts
            # or list of scalars or nested dict.
            children: list[Any] = []
            i += 1
            while i < len(lines) and (lines[i].startswith("  ") or lines[i].startswith("- ")):
                child = lines[i]
                if child.lstrip().startswith("- "):
                    item = child.lstrip()[2:]
                    if ":" in item:
                        # list of dicts
                        d: dict[str, Any] = {}
                        k0, _, v0 = item.partition(":")
                        d[k0.strip()] = _scalar(v0.strip())
                        i += 1
                        while i < len(lines) and lines[i].startswith("    "):
                            sub = lines[i].lstrip()
                            if ":" in sub:
                                k1, _, v1 = sub.partition(":")
                                d[k1.strip()] = _scalar(v1.strip())
                            i += 1
                        children.append(d)
                        continue
                    children.append(_scalar(item))
                i += 1
            result[key] = children
            continue
        result[key] = _scalar(val)
        i += 1
    return result


def _scalar(raw: str) -> Any:
    raw = raw.strip()
    if raw == "" or raw == "null":
        return None
    if raw == "true":
        return True
    if raw == "false":
        return False
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        return [_scalar(x.strip()) for x in inner.split(",")]
    if raw.startswith('"') and raw.endswith('"'):
        return raw[1:-1].replace('\\"', '"').replace("\\\\", "\\").replace("\\n", "\n")
    try:
        if "." in raw:
            return float(raw)
        return int(raw)
    except ValueError:
        return raw


# ── WikiPage ↔ markdown ──────────────────────────────────────────────────────


def parse_wiki_page(text: str, *, kind: str, slug: str) -> WikiPage:
    """Parse a wiki page markdown back to ``WikiPage``."""
    m = _FRONTMATTER_RE.match(text)
    if not m:
        return WikiPage(type=kind, id=slug, title=slug, body=text.strip())
    front_raw, body = m.group(1), m.group(2)
    front = _yaml_load(front_raw)
    body = body.lstrip()
    title = body.splitlines()[0].lstrip("# ").strip() if body else slug
    if body.startswith("# "):
        body = "\n".join(body.splitlines()[1:]).lstrip("\n")
    raw_claims = front.get("claims") or []
    claims: list[Claim] = []
    for c in raw_claims:
        if isinstance(c, dict):
            claims.append(Claim(
                text=str(c.get("text", "")),
                confidence=float(c.get("confidence", 0.5)),
                status=str(c.get("status", "candidate")),
                sources=list(c.get("sources") or []),
            ))
    return WikiPage(
        type=str(front.get("type", kind)),
        id=str(front.get("id", slug)),
        title=title,
        body=body,
        aliases=list(front.get("aliases") or []),
        confidence=float(front.get("confidence", 0.5)),
        last_updated=str(front.get("last_updated") or ""),
        sources=list(front.get("sources") or []),
        claims=claims,
        extra={k: v for k, v in front.items() if k not in {
            "type", "id", "aliases", "confidence", "last_updated", "sources", "claims",
        }},
    )


def render_wiki_page(p: WikiPage) -> str:
    """Render ``WikiPage`` to markdown."""
    front: dict[str, Any] = {
        "type": p.type,
        "id": p.id,
        "aliases": p.aliases,
        "confidence": round(p.confidence, 3),
        "last_updated": p.last_updated or now_iso(),
        "sources": p.sources,
        "claims": [
            {
                "text": c.text,
                "confidence": round(c.confidence, 3),
                "status": c.status,
                "sources": c.sources,
            }
            for c in p.claims
        ],
    }
    front.update(p.extra)
    front_yaml = _yaml_dump(front)
    body = (p.body or "").rstrip("\n")
    return f"---\n{front_yaml}\n---\n# {p.title}\n\n{body}\n"


def render_short_term_entry(e: ShortTermEntry) -> str:
    """Render a single short-term entry block."""
    tag_str = ", ".join(e.tags) if e.tags else ""
    # Pull HH:MM out of the ISO timestamp regardless of trailing 'Z' /
    # offset so the heading stays aligned.
    m = re.search(r"T(\d{2}:\d{2})", e.timestamp)
    hhmm = m.group(1) if m else e.timestamp[:5]
    head = f"## {hhmm} — type: {e.type}"
    if tag_str:
        head += f", tags: [{tag_str}]"
    foot_parts = []
    if e.session_id:
        foot_parts.append(f"session: {e.session_id}")
    foot_parts.append(f"confidence: {e.confidence:.2f}")
    foot = "<!-- " + ", ".join(foot_parts) + " -->"
    return f"{head}\n{e.text.rstrip()}\n{foot}\n"


def parse_short_term_file(text: str) -> list[ShortTermEntry]:
    """Parse a short-term daily file into entries.

    Best-effort: skips malformed blocks rather than crashing.
    """
    entries: list[ShortTermEntry] = []
    blocks = re.split(r"\n(?=## )", text.strip())
    for block in blocks:
        if not block.strip().startswith("## "):
            continue
        lines = block.splitlines()
        head = lines[0]
        meta_match = re.search(r"## (\d{2}:\d{2}) — type: ([\w\-]+)(?:, tags: \[([^\]]*)\])?", head)
        if not meta_match:
            continue
        time_part, kind, tags_str = meta_match.groups()
        body_lines = []
        foot_match = None
        for ln in lines[1:]:
            if ln.startswith("<!--") and ln.endswith("-->"):
                foot_match = ln
                continue
            body_lines.append(ln)
        body_text = "\n".join(body_lines).strip()
        session_id = ""
        confidence = 0.5
        if foot_match:
            for tok in foot_match[4:-3].strip().split(","):
                tok = tok.strip()
                if tok.startswith("session:"):
                    session_id = tok.split(":", 1)[1].strip()
                elif tok.startswith("confidence:"):
                    try:
                        confidence = float(tok.split(":", 1)[1])
                    except ValueError:
                        pass
        entries.append(ShortTermEntry(
            timestamp=time_part,
            text=body_text,
            type=kind,
            tags=[t.strip() for t in (tags_str or "").split(",") if t.strip()],
            session_id=session_id,
            confidence=confidence,
        ))
    return entries


# ── Aliases ──────────────────────────────────────────────────────────────────


def slugify(text: str) -> str:
    """Convert free text to a filesystem-safe wiki slug."""
    s = re.sub(r"[^a-zA-Z0-9\-_]+", "-", text.strip().lower())
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "untitled"
