"""Prompt text for the send_message tool (description shown to the LLM)."""
from __future__ import annotations

DESCRIPTION = (
    "Branch-to-branch communication: deliver a message to a branch, run "
    "one turn there, and (by default, async) have its reply come back to "
    "you automatically. ONE tool for spawning sub-agents, messaging other "
    "branches, and synthesizing across branches — chosen by `to`:\n"
    "\n"
    "  to=\"new\" (DEFAULT): create a fresh branch and run `message` "
    "in it — i.e. spawn a sub-agent / open a new line of work. The new "
    "branch sees ONLY `message` (a clean worker); pack what it needs into "
    "the message. Want several? call this several times — they run in "
    "parallel, each returning to you when done.\n"
    "  to=\"new:SID:MSG_ID\": fork a new branch off an existing node "
    "(it inherits the chain up to that node), then run `message`.\n"
    "  to=\"SID:HEAD\": deliver `message` to an existing branch and "
    "trigger it to respond. If the target is busy running a turn, the "
    "message is queued and processed when that turn ends.\n"
    "  to=\"<branch name>\": address a named branch directly (exact "
    "name, or a unique prefix — see list_branches for names).\n"
    "\n"
    "When you RECEIVE a message from another branch (it starts with "
    "\"[message from SID:HEAD]\"), replying is optional — the message is "
    "already delivered; reply only when you have something substantive "
    "to add, and when unsure, don't reply.\n"
    "\n"
    "wait=False (DEFAULT): returns a delivery id immediately; you are NOT "
    "blocked — keep working. The target's reply is delivered back to you "
    "as a new message automatically when it finishes. wait=True: block "
    "and return the reply text directly.\n"
    "\n"
    "Use this to offload sub-tasks, run parallel explorations, or hand a "
    "message to another agent/branch."
)
