"""Auto-generated by create(). Description: Analyze text sentiment. Return positive, negative, or neutral."""

from agentic.function import agentic_function

@agentic_function
def sentiment(text: str) -> str:
    """Analyze the sentiment of the given text.

    Args:
        text: The text to analyze for sentiment.

    Returns:
        One of 'positive', 'negative', or 'neutral'.
    """
    result = runtime.exec(content=[
        {"type": "text", "text": f"Analyze the sentiment of the following text. Respond with exactly one word: positive, negative, or neutral.\n\nText: {text}"}
    ])
    label = result.strip().lower()
    if label not in ("positive", "negative", "neutral"):
        for candidate in ("positive", "negative", "neutral"):
            if candidate in label:
                return candidate
        return "neutral"
    return label
