"""Auto-generated by create(). Description: Count words in a text string"""

from agentic.function import agentic_function

def word_count(text: str) -> int:
    """Count the number of words in a text string.

    Args:
        text: The input text string to count words in.

    Returns:
        The number of words in the text.
    """
    return len(text.split())
